# Generated by Django 2.2.19 on 2023-03-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230321_0140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Связь ингредиентов и рецептов', 'verbose_name_plural': 'Связь ингредиентов и рецептов'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Связь тегов и рецептов', 'verbose_name_plural': 'Связь тегов и рецептов'},
        ),
    ]
